### PR TITLE
sorting

### PR DESCRIPTION
**Pull request by jstavh**
sorting by block height

### CODE REVIEW

**Comment by robinbb** [comment]
@mxnnn if you review this, consider ignoring this page and just using 'git diff -w' so that the many whitespace changes are ignored. This is really a 4-line change.

**Review by robinbb — CHANGES_REQUESTED** [review]
This PR merely sorts the pages, no the entire results set. In other words, block heights on page 1 will have values lower than block heights on page 2.

**Comment by jstavh** [comment]
> @robinbb  if you review this, consider ignoring this page and just using 'git diff -w' so that the many whitespace changes are ignored. This is really a 4-line change.

Yes, prettier seems re-arrange/re-format and consider these real changes. Similar to the commits we were reviewing regarding timestamps. I was trying to fix with as little code additions as possible.

**Comment by jstavh** [comment]
> sorts the pages, no the entire results set. In other words, block heights on page 1 will have values lower than block heights on page 2.

Working on fixing this

**Comment by jstavh** [comment]
@robinbb @mxnnn I believe recent/above commit fixes sorting the entire set.

**Review by trevorbernard — APPROVED** [review]

**Pull request merged**
