### PR TITLE
feat(ui): updated design & migrate to next 13

### PR DESCRIPTION
**Pull request by 52**
# Overview
This PR incorporates a redesigned UI along with a migration to Next 13's app router.
Additionally, it removes technical debt accrued prior to our transition to a maintenance phase.

**Note**: It's artificially bloated - files in `components/core` do not need to be reviewed as they are radix-ui primitives.

## Changes
- Migrated components to Tailwind & Radix
- Migrated pages to Next 13's app router
- Migrated & extended tests to increase coverage
- Remove unused features (MUI - Storybook - Typeshare)

## Preview
https://mina-on-chain-voting-web-git-feat-ui-update-5bf575-team-granola.vercel.app/
https://github.com/Granola-Team/mina-on-chain-voting/assets/85909615/30f5938d-f512-4cef-ad99-b5103194bd03

### CODE REVIEW

**Comment by trevorbernard** [comment]
I added comments offline

**Comment by jstavh** [comment]
Great improvements to UI/UX! Just 3 thoughts:
- Should we add some color on the root README regarding frontend changes? 
- Could key be just MIP ie `MIP1` instead of `1 - MIP1`? 
- If we are going to click the button to go to the results page, then should we label the button `Results Page [->]` or just make the whole row clickable?
Overall, awesome stuff!

**Review by jstavh — COMMENTED** [review]
Great improvements to UI/UX! Just 3 thoughts:
- Should we add some color on the root README regarding frontend changes? 
- Could key be just MIP ie `MIP1` instead of `1 - MIP1`? 
- If we are going to click the button to go to the results page, then should we label the button `Results Page [->]` or just make the whole row clickable?

Overall, awesome stuff!

**Review by jstavh — APPROVED** [review]
@52 This PR adds lots of value, so let's merge, then later either do or not the comments if we want to :)

**Pull request merged**
