### PR TITLE
Log level set from env var

### PR DESCRIPTION
**Pull request by jstavh**
Add the ability to change log level from env variables and also from Docker.

### CODE REVIEW

**Review by 52 — CHANGES_REQUESTED** [review]
You don't need new env variables.
Change the following line:

```rs
pub(crate) fn init_tracing() {
    tracing_subscriber::fmt::Subscriber::builder()
        .with_env_filter(EnvFilter::new(
            "mina_governance_server=warn,tower_http=warn",
        ))
        ...
}
```
To:
```rs
pub(crate) fn init_tracing() {
    tracing_subscriber::fmt::Subscriber::builder()
        .with_env_filter(EnvFilter::from_default_env())
        ...
}
```

You can then trigger the log level by using **RUST_LOG**:
```shell
RUST_LOG=info cargo run --release
RUST_LOG=debug ...
RUST_LOG=trace ...
```

**Comment by jstavh** [comment]
> You don't need new env variables. Change the following:
> 
> ```rust
> pub(crate) fn init_tracing() {
>     tracing_subscriber::fmt::Subscriber::builder()
>         .with_env_filter(EnvFilter::new(
>             "mina_governance_server=warn,tower_http=warn",
>         ))
>         ...
> }
> ```
> 
> to...
> 
> ```rust
> pub(crate) fn init_tracing() {
>     tracing_subscriber::fmt::Subscriber::builder()
>         .with_env_filter(EnvFilter::from_default_env())
>         ...
> }
> ```
> 
> You can then trigger the log level by using **RUST_LOG**:
> 
> ```shell
> RUST_LOG=info cargo run --release
> RUST_LOG=debug ...
> RUST_LOG=trace ...
> ...
> ```

@52 @robinbb Gotcha and that works for both the server logs and tower_http? Does you suggestion also help set log levels as I added in the `docker-compose.yaml` file?

**Comment by 52** [comment]
> > You don't need new env variables. Change the following:
> > ```rust
> > pub(crate) fn init_tracing() {
> >     tracing_subscriber::fmt::Subscriber::builder()
> >         .with_env_filter(EnvFilter::new(
> >             "mina_governance_server=warn,tower_http=warn",
> >         ))
> >         ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to...
> > ```rust
> > pub(crate) fn init_tracing() {
> >     tracing_subscriber::fmt::Subscriber::builder()
> >         .with_env_filter(EnvFilter::from_default_env())
> >         ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can then trigger the log level by using **RUST_LOG**:
> > ```shell
> > RUST_LOG=info cargo run --release
> > RUST_LOG=debug ...
> > RUST_LOG=trace ...
> > ...
> > ```
> 
> @52 Gotcha and that works for both the server logs and tower_http? Does your suggestion also help set log levels as I added in the `docker-compose.yaml` file? We may want to be able to control this directly from env variables depending on @robinbb thoughts.

Sure, you can configure all & add it to the docker compose file - another example:
```sh
RUST_LOG="mina_governance_server=debug,tower_http=trace" cargo run --release
```

**Comment by jstavh** [comment]
> > > You don't need new env variables. Change the following:
> > > ```rust
> > > pub(crate) fn init_tracing() {
> > >     tracing_subscriber::fmt::Subscriber::builder()
> > >         .with_env_filter(EnvFilter::new(
> > >             "mina_governance_server=warn,tower_http=warn",
> > >         ))
> > >         ...
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to...
> > > ```rust
> > > pub(crate) fn init_tracing() {
> > >     tracing_subscriber::fmt::Subscriber::builder()
> > >         .with_env_filter(EnvFilter::from_default_env())
> > >         ...
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can then trigger the log level by using **RUST_LOG**:
> > > ```shell
> > > RUST_LOG=info cargo run --release
> > > RUST_LOG=debug ...
> > > RUST_LOG=trace ...
> > > ...
> > > ```
> > 
> > 
> > @52 Gotcha and that works for both the server logs and tower_http? Does your suggestion also help set log levels as I added in the `docker-compose.yaml` file? We may want to be able to control this directly from env variables depending on @robinbb thoughts.
> 
> Sure, you can configure all & add it to the docker compose file - another example:
> 
> ```shell
> RUST_LOG="mina_governance_server=debug,tower_http=trace" cargo run --release
> ```

@52 Your suggestion is for when running from the server, right, but when you run from Docker such as `docker-compose --profile server-db up` then don't you need the changes I made in the docker-compose.yaml file?

**Comment by robinbb** [comment]
The RUST_LOG env var is not picked up, seemingly. The only way that I can get traces is via manually changing the settings in the code and recompiling.

**Comment by robinbb** [comment]
Also, I'm getting a 404 page for '/api/proposals/4/results' but there's no evidence of an error in the tracing.

**Comment by robinbb** [comment]
Resolved by https://github.com/Granola-Team/mina-on-chain-voting/pull/295

**Comment by robinbb** [comment]
Resolved by https://github.com/Granola-Team/mina-on-chain-voting/pull/295

**Pull request closed without merging**
