### PR TITLE
feat: Add clickable rows 

### PR DESCRIPTION
**Pull request by 52**
## Changes
- Makes rows of the proposal table "clickable" & route to their respective page.

### CODE REVIEW

**Comment by robinbb** [comment]
@52 What's the plan with this PR? Will you resolve the build errors?

**Comment by 52** [comment]
> @52 What's the plan with this PR? Will you resolve the build errors?

Resolved. 👍

**Review by jstavh — CHANGES_REQUESTED** [review]
Reviewing now

**Review by jstavh — APPROVED** [review]
Referencing the work done here = https://github.com/Granola-Team/mina-on-chain-voting/pull/258

**Pull request merged**
